name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create package.json
        run: echo '{}' > package.json

      - name: Install semantic-release and plugins
        run: npm install semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/git @semantic-release/github -D

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build self-contained executable
        run: dotnet publish ./MyProject/MyProject.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npx semantic-release
